// screens/qr-code/styles/QRScannerStyles.ts
import { getFontFamily } from "@/constants/typography";
import { COLORS } from "@/screens/dashboard/constants/color";
import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.black },
  camera: { flex: 1 },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingTop: Platform.OS === "ios" ? 50 : 30,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  closeButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  flashButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: getFontFamily("semibold"),
    color: COLORS.white,
  },
  scanArea: {
    width: 280,
    height: 280,
    alignSelf: "center",
    marginTop: 80,
    position: "relative",
  },
  cornerTL: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 40,
    height: 40,
    borderTopWidth: 4,
    borderLeftWidth: 4,
    borderColor: COLORS.primary.main,
  },
  cornerTR: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 40,
    height: 40,
    borderTopWidth: 4,
    borderRightWidth: 4,
    borderColor: COLORS.primary.main,
  },
  cornerBL: {
    position: "absolute",
    bottom: 0,
    left: 0,
    width: 40,
    height: 40,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
    borderColor: COLORS.primary.main,
  },
  cornerBR: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 40,
    height: 40,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderColor: COLORS.primary.main,
  },
  instruction: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: getFontFamily("regular"),
    textAlign: "center",
    marginTop: 40,
  },
  gpsStatus: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    paddingHorizontal: 20,
    paddingVertical: 8,
    backgroundColor: "rgba(0,0,0,0.6)",
    borderRadius: 20,
    alignSelf: "center",
  },
  gpsErrorStatus: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    paddingHorizontal: 20,
    paddingVertical: 8,
    backgroundColor: "rgba(0,0,0,0.6)",
    borderRadius: 20,
    alignSelf: "center",
  },
  gpsText: {
    color: COLORS.warning.main,
    fontSize: 12,
    marginLeft: 8,
    fontFamily: getFontFamily("regular"),
  },
  gpsSuccessText: {
    color: COLORS.success.main,
    fontSize: 12,
    marginLeft: 8,
    fontFamily: getFontFamily("regular"),
  },
  gpsErrorText: {
    color: COLORS.error.main,
    fontSize: 12,
    marginLeft: 8,
    fontFamily: getFontFamily("regular"),
  },
  verifyingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.8)",
    justifyContent: "center",
    alignItems: "center",
  },
  verifyingText: {
    color: COLORS.white,
    marginTop: 10,
    fontSize: 16,
    fontFamily: getFontFamily("medium"),
  },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: COLORS.background,
  },
  text: {
    fontSize: 16,
    marginTop: 10,
    fontFamily: getFontFamily("medium"),
    color: COLORS.gray[900],
  },
  subText: {
    fontSize: 14,
    color: COLORS.gray[600],
    textAlign: "center",
    marginTop: 8,
    fontFamily: getFontFamily("regular"),
  },
  button: {
    backgroundColor: COLORS.primary.main,
    paddingHorizontal: 30,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 20,
  },
  buttonText: {
    color: COLORS.white,
    fontSize: 16,
    fontFamily: getFontFamily("semibold"),
  },
  // ✅ Styles ajoutés pour le PermissionRequest
  secondaryButton: {
    backgroundColor: COLORS.gray[200],
    marginTop: 12,
  },
  secondaryButtonText: {
    color: COLORS.gray[800],
    fontSize: 16,
    fontFamily: getFontFamily("semibold"),
  },
  permissionIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: `${COLORS.error.main}15`,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  permissionTitle: {
    fontSize: 20,
    fontFamily: getFontFamily('bold'),
    color: COLORS.gray[900],
    marginBottom: 8,
  },
  permissionMessage: {
    fontSize: 14,
    fontFamily: getFontFamily('regular'),
    color: COLORS.gray[600],
    textAlign: 'center',
    marginBottom: 24,
    paddingHorizontal: 20,
  },
});
